# pubspec.yaml
name: flutter_navigation_example
description: A Flutter app for navigation and recording time.
version: 1.0.0

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.4
  intl: ^0.17.0
  provider: ^6.0.1
  sqflite: ^2.3.0
  path_provider: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true